apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
spec:
  group: etcd.database.coreos.com
  names:
    kind: EtcdCluster
    listKind: EtcdClusterList
    plural: etcdclusters
    shortNames:
    - etcdclus
    - etcd
    singular: etcdcluster
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
              version:
                type: string
          status:
            type: object
        required: [spec]
    additionalPrinterColumns:
    - name: Size
      type: integer
      description: The size of the cluster
      jsonPath: .spec.size
    - name: Version
      type: string
      description: The version of the cluster
      jsonPath: .spec.version
    - name: Status
      type: string
      description: The status of the cluster
      jsonPath: .status.phase
    subresources:
      status: {}